version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: blogs_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001 # API port
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password # mysql password for container
      HOSTNAME: db
      JWT_SECRET: secretJWT
  db:
    container_name: blogs_api_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306 # mysql container port
      - 33060:33060 # mysql container port 2
    environment:
      MYSQL_ROOT_PASSWORD: password # mysql password for container

networks:
  default:
    name: blogs_api_net